# Generated by Django 5.2.9 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='CSE', max_length=100),
        ),
    ]
