# Generated by Django 5.2.9 on 2026-01-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=10)),
                ('file_type', models.CharField(choices=[('SLIDE', 'Lecture Slide'), ('PDF', 'PDF Document'), ('CODE', 'Code File'), ('NOTE', 'Note/Reference'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('text_content', models.TextField(blank=True, help_text='For notes or code snippets if no file is uploaded')),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.topic')),
            ],
        ),
    ]
